application: automatic-diary
version: 3
runtime: go
api_version: go1

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /assets
  static_dir: static

# don't put auth here - postmaster needs to be able to deliver mails!
- url: /.*
  script: _go_app
